server:
  port: 8082
spring:
  application:
    name: ms-oauth2-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/social_link?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000
    database: 1
    password: 123456

  swagger:
    base-package: org.example.dinner.oauth2
    title: Api document

client:
  oauth2:
    client-id: appId
    secret: 123456
    grant_types:
      - password
      - refresh_token

    token-validity-time: 3600
    refresh-token-validity-time: 3600

    scopes:
      - api
      - all
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

mybatis:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"